/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.view {
    export class ChooseLevelUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/ChooseLevel");
        }
    }
    REG("ui.view.ChooseLevelUI",ChooseLevelUI);
    export class MianViewUI extends Scene {
		public btn_gameStar:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/MianView");
        }
    }
    REG("ui.view.MianViewUI",MianViewUI);
}